pipeline {
  agent {
    docker { image 'node:17-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        echo 'whoami'
        echo 'username'
        sh 'node --version'
      }
    }
  }
}
